### ISSUE TITLE
Failed to open device

### ISSUE THREAD

**Issue by ababacz** [profanum429/v800_downloader#10]
Hello,

I have just installed v800_downloader. Unfortunately, every time I try to connect with my watch I get "Failed to open device".

- Watch is connected via cable to USB port.
- I try both with FlowSync active and disabled
- I try both when FlowSync is synchronizing and not
- Win8
- SW: 1.5.1
- there is a batch of trainings done after last system update on the watch.

Thank you in advance for help.

**Comment by ababacz** [comment]
Hello again,

issue is caused by WIN8. I retried on XP and it works indeed! Perfect thanks.

(another ticket on the way)

**Comment by paufonseca** [comment]
I try on W 8.1 and it works, Polar 1.5
