### ISSUE TITLE
Cant export Sports without GPS

### ISSUE THREAD

**Issue by Roxxor91** [profanum429/v800_downloader#24]
Hi!
I try to export sports without GPS (Swimming, other indoorsports). The sessions are listed and files are getting pulled from the watch. Just the conversion is not successful.
The file attached includes logs and files from a tried export of "other indoorsports".

Would be nice to get a file with laps/time and HR.

Thank you!
[Other_Indoorsport.zip](https://github.com/profanum429/v800_downloader/files/504191/Other_Indoorsport.zip)

**Comment by pcolby** [comment]
Hi @Roxxor91,

I have a fix that should work for this, on my v800_downloader fork (https://github.com/pcolby/v800_downloader/commit/5c761fcb3caaa3e81ece54d5f7cc9bab3c99d82a).

Cheers.

**Comment by Roxxor91** [comment]
Sorry for the late reply.

But the fix worked perfectly :)

Thanks! :)
