### ISSUE TITLE
Multiple work-outs

### ISSUE THREAD

**Issue by dtougas** [profanum429/v800_downloader#3]
OK, I tried downloading workouts from my M400 again today. I had a day that had two workouts, one in the morning with GPS but no HR, and another in the afternoon with HR, but no GPS. The downloader only sees the morning workout, but not the afternoon one. Syncing my workouts with Polar Flow shows both. Any thoughts on why this might be?

**Comment by profanum429** [comment]
Fixed in Release6 hopefully, looking for samples now instead of routes to say if there is a session.
