### ISSUE TITLE
No downloads showing up after firmware upgrade

### ISSUE THREAD

**Issue by dtougas** [profanum429/v800_downloader#5]
I just upgraded my M400 firmware today to the latest version (1.3), and I can no longer see any workouts in the downloader list. I see there was a new update for the V800 as well, so I am curious if anyone else is experiencing similar issues.

**Comment by profanum429** [comment]
Have you done any new activities since the firmware update? I know on the V800 whenever we get a firmware update it erases the previous full session data and leaves only the statistics.

**Comment by dtougas** [comment]
Ah, OK that makes sense. No, I hadn't done any activities since the update. I had intended on downloading the data after the update, but apparently that wasn't a good idea. Thanks for the heads-up.
